# Generated by Django 5.1 on 2024-10-15 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_car_remove_profile_unit_number_booking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='make',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.IntegerField(),
        ),
    ]
